.TH man_3_printf.1
.SH printf
Prints content on the screen

.SH LIBRARY

The printf function is included in the standard library.

.SH DESCRIPTION
.B
 
The printf function is a function that formats and prints a series of characters and values ​​to the standard output stream stdout.

 --version: output version information and exit

The format, as its name suggests, represents what the output will consist of Here are the main ones to use

%s: used to display a string

%d: used to display an integer

%c: used to display a character

%f: used to display a decimal number

%p: used to specify a pointer

\n: used to return to the next line

\\: used to return to the next line, inverse to escape the character that follows it

.SH
Exemple

_printf("%d")


.SH 
AUTHOR
    Robin, Ilan


.SH
Exemple
    Here is an example of how to use the command: printf("%d\n")


















